### ISSUE TITLE
Manuális tesztek

### ISSUE THREAD

**Issue by henczi** [BME-MIT-IET/undefined-is-NaN-iet-2018#15]
Manuális tesztek megtervezése, végrehajtása és dokumentálása

**Comment by nagybalint001** [comment]
union_find.count_islands
Kipróbáltam, és nem igazán úgy működik, mint ahogy elvárnánk.
Először is nem veszi figyelembe a függvény paraméterei közül a sorok és oszlopok számát.
Másik furcsaság, hogy nem egy számot ad vissza eredményként, hanem egy tömböt, amikben számok vannak.

**Comment by henczi** [comment]
Igen...
Ha csak ez az egy lenne, ami nem úgy működik, ahogy kéne...

**Comment by henczi** [comment]
Manuális teszt a wiki oldalon
