### ISSUE TITLE
Tesztek kódlefedettsége

### ISSUE THREAD

**Issue by henczi** [BME-MIT-IET/undefined-is-NaN-iet-2018#16]
Tesztek kódlefedettségének mérése és ez alapján tesztkészlet bővítése

**Comment by henczi** [comment]
A kódlefedettség ellenőrzéséhez érdemes a `pytest-cov` csomagot telepíteni, és azt a `pytest --cov --cov-report=html` parancs segítségével futtani. Ez generál egy `htmlcov` mappát amiben az `index.html`-t megnyitva látható a lefedettség az egyes fájlokra kattintva pedig a forráskódban mutatja, hogy mely sorok nem futottak le.

**Comment by henczi** [comment]
A repo mappáján kívül `coverage run --source <REPO> -m py.test <REPO>/`, majd `coverage report` vagy `coverage html` egy átfogóbb képet ad.

**Comment by nagybalint001** [comment]
Csak a tests mappában lévő tesztek futatásához: `pytest tests --cov --cov-report=html`

**Comment by olahkoo** [comment]
Írtam a graph mappában lévő fájlokhoz még néhány tesztet. A satisfiability.py-ban lévő kód nem futott le, ugyanis egy dictionarynek hívták az iteritems() függvényét, ami python3-tól nem helyes, helyette az items() függvényt kell használni. A tesztelés tehát hasznos volt, nőtt a kódlefedettség, a hibát pedig természetesen javítottam.

**Comment by henczi** [comment]
done
