### ISSUE TITLE
Ismerkedés a projekttel

### ISSUE THREAD

**Issue by nagybalint001** [BME-MIT-IET/undefined-is-NaN-iet-2018#2]
A projekt felépítésének tanulmányozása, majd egy-két egyszerűbb példakód készítése.

**Comment by nagybalint001** [comment]
#8 tartalmaz néhány példát

**Comment by balix18** [comment]
Commit 795d6587a1fe23585d3bdf1144f4fa2700538790 is tartalmaz példát

**Comment by balix18** [comment]
PR #10 is tartalmaz példát (LinkedList)
