### ISSUE TITLE
Statikus analízis

### ISSUE THREAD

**Issue by nagybalint001** [BME-MIT-IET/undefined-is-NaN-iet-2018#4]
Statikus analízis eszköz futtatása és a jelzett hibák átnézése.

**Comment by nagybalint001** [comment]
Beüzemeltem egy ilyen eszközt:
https://sonarcloud.io/dashboard?id=algorithms

**Comment by nagybalint001** [comment]
Úgy tűnik, hogy a legtöbb probléma, amit a sonarcloud jelzett, négy csoportba foglalható
* if feltételek egybevonása a szülő feltételeivel
* kommentek törlése
* változó elnevezése nem megfelelő
* túl komplex az algoritmus

**Comment by nagybalint001** [comment]
pylint több formai "problémát" is jelzett:
* whitespace használat nem megfelelő
* változók és konstansok elnevezései nem követik a konvenciókat

Alapvetően ezek szerintem nem számítanak problémának, hogyha az egész projektben mindenki egységesen (egyformán) követi ezeket a "saját" konvenciókat.

**Comment by olahkoo** [comment]
A sonarcloud által jelzett problémákat átnéztem, és úgy ítéltem, leginkább a felesleges kommentek törlésével, illetve a túl hosszú függvények tördelésével érdemes foglalkozni (ahol ez lehetséges). A változónevek a projektben egységesen vannak elnevezve, így azon nem érdemes változtatni. Az if-ek egybevonását sem tartom indokoltnak, jelen formájában jobban olvasható a kód. Erre jó példa az alábbi képen látható:

![if_merge](https://user-images.githubusercontent.com/23548174/39491031-29057346-4d8b-11e8-963a-70823db73784.JPG)

**Comment by olahkoo** [comment]
Azokra a fájlokra, amelyekre írtunk példakódot, a pylint által jelzett hibákat nagyrészt kijavítottam. Ezek nagy része a rossz szóközhasználat volt, de volt néhány más jellegű hiba is, amit sikerült javítani (pl. len(list) == 0 használata a lista ürességének ellenőrzésére).
