### ISSUE TITLE
Manuális kód átvizsgálás

### ISSUE THREAD

**Issue by nagybalint001** [BME-MIT-IET/undefined-is-NaN-iet-2018#5]
Manuális kód átvizsgálás elvégzése az alkalmazás egy részére.

**Comment by nagybalint001** [comment]
Végtelen ciklusba fut itt a program helyes bemenet esetében:
https://github.com/BME-MIT-IET/undefined-is-NaN-iet-2018/blob/795d6587a1fe23585d3bdf1144f4fa2700538790/calculator/math_parser.py#L136-L143

Nem a legjobb ez a komment, mivel ebben a formában (szóközökkel) nem helyes input
https://github.com/BME-MIT-IET/undefined-is-NaN-iet-2018/blob/795d6587a1fe23585d3bdf1144f4fa2700538790/calculator/math_parser.py#L4-L16

**Comment by henczi** [comment]
A linkelt lista tartalmaz egy egyirányú és egy kétirányú listát is, amiben .value tartalmazza a node értékét, de a legtöbb helyen .val néven van hivatkozva
https://github.com/BME-MIT-IET/undefined-is-NaN-iet-2018/blob/795d6587a1fe23585d3bdf1144f4fa2700538790/linkedlist/linkedlist.py#L14-L24
https://github.com/BME-MIT-IET/undefined-is-NaN-iet-2018/blob/795d6587a1fe23585d3bdf1144f4fa2700538790/linkedlist/is_sorted.py#L11-L19
Illetve több helyen - feleslegesen - definiálva van egy Node osztály (egyirányú linkeléssel)

**Comment by henczi** [comment]
Ha a linkelt listában kör van, akkor a kiíratás végtelen ciklusba fut.
https://github.com/BME-MIT-IET/undefined-is-NaN-iet-2018/blob/795d6587a1fe23585d3bdf1144f4fa2700538790/linkedlist/kth_to_last.py#L65-L71
